// Generated by scripts/gen-project-names.mjs from src/i18n/*.json — do not edit by hand.
export const PROJECT_NAMES: Record<string, Record<"en" | "ar" | "fa" | "fr" | "ru", string>> = {
  "beylikduzu-living": {
    "en": "Lotus Yaşam",
    "ar": "لوتس ياشام",
    "fa": "لوتوس یاشام",
    "fr": "Lotus Yaşam",
    "ru": "Lotus Yaşam"
  },
  "diamond-marin": {
    "en": "Diamond Marin",
    "ar": "دايموند مارين",
    "fa": "دایموند مارین",
    "fr": "Diamond Marin",
    "ru": "Diamond Marin"
  },
  "lotus-manzara-guzelce": {
    "en": "Lotus Manzara Güzelce",
    "ar": "لوتس مانزارا غوزلجه",
    "fa": "لوتوس مانزارا گوزلجه",
    "fr": "Lotus Manzara Güzelce",
    "ru": "Lotus Manzara Güzelce"
  },
  "lotus-manzara-beylikduzu": {
    "en": "Lotus Manzara Beylikdüzü",
    "ar": "لوتس مانزارا بيليكدوزو",
    "fa": "لوتوس مانزارا بیلیک‌دوزو",
    "fr": "Lotus Manzara Beylikdüzü",
    "ru": "Lotus Manzara Beylikdüzü"
  },
  "lotus-yali": {
    "en": "Lotus Yalı",
    "ar": "لوتس يالي",
    "fa": "لوتوس یالی",
    "fr": "Lotus Yalı",
    "ru": "Lotus Yalı"
  },
  "cadde-ispartakule": {
    "en": "Cadde Ispartakule",
    "ar": "جادّة إسبارتاكولي",
    "fa": "جاده اسپارتاکوله",
    "fr": "Cadde Ispartakule",
    "ru": "Cadde Ispartakule"
  },
  "lotus-sisli": {
    "en": "Lotus Şişli",
    "ar": "لوتس شيشلي",
    "fa": "لوتوس شیشلی",
    "fr": "Lotus Şişli",
    "ru": "Lotus Şişli"
  },
  "lotus-koru-2": {
    "en": "Lotus Koru 2",
    "ar": "لوتس كورو 2",
    "fa": "لوتوس کورو 2",
    "fr": "Lotus Koru 2",
    "ru": "Lotus Koru 2"
  },
  "lotus-istanbul": {
    "en": "Lotus İstanbul",
    "ar": "لوتس إسطنبول",
    "fa": "لوتوس استانبول",
    "fr": "Lotus İstanbul",
    "ru": "Lotus İstanbul"
  },
  "lotus-koru-1": {
    "en": "Lotus Koru 1",
    "ar": "لوتس كورو 1",
    "fa": "لوتوس کورو 1",
    "fr": "Lotus Koru 1",
    "ru": "Lotus Koru 1"
  },
  "marmara-haven-villa": {
    "en": "Marmara Haven Villa",
    "ar": "فيلا مرمرة هيفن",
    "fa": "ویلا مرمرا هیون",
    "fr": "Marmara Haven Villa",
    "ru": "Marmara Haven Villa"
  }
};
