// Generated by scripts/gen-project-names.mjs from src/i18n/*.json — do not edit by hand.
export const PROJECT_NAMES: Record<string, Record<"en" | "ar" | "fr" | "ru", string>> = {
  "beylikduzu-living": {
    "en": "Beylikdüzü Living",
    "ar": "بيليكدوزو ليفينغ",
    "fr": "Beylikdüzü Living",
    "ru": "Beylikdüzü Living"
  },
  "diamond-marin": {
    "en": "Diamond Marin",
    "ar": "دايموند مارين",
    "fr": "Diamond Marin",
    "ru": "Diamond Marin"
  },
  "lotus-manzara-guzelce": {
    "en": "Lotus Manzara Güzelce",
    "ar": "لوتس مانزارا غوزلجه",
    "fr": "Lotus Manzara Güzelce",
    "ru": "Lotus Manzara Güzelce"
  },
  "lotus-manzara-beylikduzu": {
    "en": "Lotus Manzara Beylikdüzü",
    "ar": "لوتس مانزارا بيليكدوزو",
    "fr": "Lotus Manzara Beylikdüzü",
    "ru": "Lotus Manzara Beylikdüzü"
  },
  "lotus-yali": {
    "en": "Lotus Yalı",
    "ar": "لوتس يالي",
    "fr": "Lotus Yalı",
    "ru": "Lotus Yalı"
  },
  "cadde-ispartakule": {
    "en": "Cadde Ispartakule",
    "ar": "جادّة إسبارتاكولي",
    "fr": "Cadde Ispartakule",
    "ru": "Cadde Ispartakule"
  },
  "lotus-sisli": {
    "en": "Lotus Şişli",
    "ar": "لوتس شيشلي",
    "fr": "Lotus Şişli",
    "ru": "Lotus Şişli"
  },
  "lotus-koru-2": {
    "en": "Lotus Koru 2",
    "ar": "لوتس كورو 2",
    "fr": "Lotus Koru 2",
    "ru": "Lotus Koru 2"
  },
  "lotus-istanbul": {
    "en": "Lotus İstanbul",
    "ar": "لوتس إسطنبول",
    "fr": "Lotus İstanbul",
    "ru": "Lotus İstanbul"
  },
  "lotus-koru-1": {
    "en": "Lotus Koru 1",
    "ar": "لوتس كورو 1",
    "fr": "Lotus Koru 1",
    "ru": "Lotus Koru 1"
  },
  "marmara-haven-villa": {
    "en": "Marmara Haven Villa",
    "ar": "فيلا مرمرة هيفن",
    "fr": "Marmara Haven Villa",
    "ru": "Marmara Haven Villa"
  }
};
