"""Builds src/data/istanbulMap.ts — the project-page map of Istanbul (district outlines, main roads,
Bosphorus bridges, landmarks). Run from the repo root:  python3 scripts/istanbul-map/build.py
Roads and bridges are in roads.py (lat, lon waypoints); landmarks and shield spots are below."""
import json, math, os, sys, urllib.request
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = "https://raw.githubusercontent.com/ozanyerli/istanbul-districts-geojson/main/istanbul-districts.json"
CACHE = os.path.join(HERE, "istanbul-districts.json")
if not os.path.exists(CACHE):
    urllib.request.urlretrieve(SRC, CACHE)
d = json.load(open(CACHE))
TOL = float(sys.argv[1]) if len(sys.argv) > 1 else 1.0
W = 1000
K = math.cos(math.radians(41.05))
pts = [c for f in d["features"] for poly in (f["geometry"]["coordinates"] if f["geometry"]["type"]=="MultiPolygon" else [f["geometry"]["coordinates"]]) for ring in poly for c in ring]
minx = min(p[0] for p in pts); maxx = max(p[0] for p in pts); miny = min(p[1] for p in pts); maxy = max(p[1] for p in pts)
PAD = 12
scale = (W - 2*PAD) / ((maxx - minx) * K)
H = round((maxy - miny) * scale + 2*PAD)
def proj(c): return ((c[0]-minx)*K*scale + PAD, (maxy-c[1])*scale + PAD)
def dp(points, tol):
    if len(points) < 3: return points
    a, b = points[0], points[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]; L = math.hypot(dx, dy)
    best, idx = -1, 0
    for i in range(1, len(points)-1):
        p = points[i]
        dist = abs(dy*p[0]-dx*p[1]+b[0]*a[1]-b[1]*a[0])/L if L else math.hypot(p[0]-a[0], p[1]-a[1])
        if dist > best: best, idx = dist, i
    if best > tol:
        return dp(points[:idx+1], tol)[:-1] + dp(points[idx:], tol)
    return [a, b]
def area(r): return abs(sum(r[i][0]*r[i-1][1]-r[i-1][0]*r[i][1] for i in range(len(r))))/2
def centroid(r):
    A = 0; cx = cy = 0
    for i in range(len(r)):
        x0,y0 = r[i-1]; x1,y1 = r[i]; c = x0*y1-x1*y0; A += c; cx += (x0+x1)*c; cy += (y0+y1)*c
    A /= 2
    return (cx/(6*A), cy/(6*A))
out = {}; cents = {}
for f in d["features"]:
    name = f["properties"]["name"]
    polys = f["geometry"]["coordinates"] if f["geometry"]["type"]=="MultiPolygon" else [f["geometry"]["coordinates"]]
    parts = []; biggest = None
    for poly in polys:
        for ri, ring in enumerate(poly):
            if ri > 0: continue  # holes are negligible at this scale
            r = [proj(c) for c in ring]
            a = area(r)
            if a < 6 and name != "Adalar": continue
            if a < 1.5: continue
            if biggest is None or a > biggest[0]: biggest = (a, r)
            # split closed ring in two halves for DP stability
            h = len(r)//2
            s = dp(r[:h+1], TOL)[:-1] + dp(r[h:], TOL)
            if len(s) < 4: continue
            parts.append("M" + "L".join(f"{x:.0f},{y:.0f}" if TOL >= 1 else f"{x:.1f},{y:.1f}" for x, y in s[:-1]) + "Z")
    out[name] = "".join(parts)
    cents[name] = tuple(round(v, 1) for v in centroid(biggest[1]))
ts = ["// Generated from the Istanbul district boundaries (github.com/ozanyerli/istanbul-districts-geojson),",
      "// projected to an SVG viewBox and simplified. Generated by scripts/istanbul-map/build.py — edit that, not this file.",
      f"export const MAP_WIDTH = {W};", f"export const MAP_HEIGHT = {H};", "",
      "/** SVG path per district, keyed by its Turkish name (as used in `Project.district`). */",
      "export const DISTRICT_PATHS: Record<string, string> = {"]
ts += [f"  {json.dumps(k, ensure_ascii=False)}: {json.dumps(v)}," for k, v in sorted(out.items())]
ts += ["};", "", "/** Visual centre of each district (centroid of its largest part), in viewBox units. */",
       "export const DISTRICT_CENTERS: Record<string, [number, number]> = {"]
ts += [f"  {json.dumps(k, ensure_ascii=False)}: [{v[0]}, {v[1]}]," for k, v in sorted(cents.items())]
ts += ["};", ""]
exec(open(os.path.join(HERE, "roads.py")).read())
P = lambda lat, lon: tuple(round(v, 1) for v in proj((lon, lat)))
LANDMARKS = [
  ("istAirport", "airport", 41.2753, 28.7519),
  ("sawAirport", "airport", 40.8986, 29.3092),
  ("mallOfIstanbul", "mall", 41.0636, 28.8090),
  ("marmaraPark", "mall", 41.0010, 28.6570),
  ("florya", "landmark", 40.9760, 28.7850),
  ("taksim", "landmark", 41.0370, 28.9850),
  ("sultanahmet", "landmark", 41.0086, 28.9802),
]
SHIELDS = {
  "e5": [(41.040,28.45),(41.005,28.88),(40.930,29.15)],
  "e80": [(41.090,28.55),(41.100,28.99),(40.975,29.22)],
  "o7": [(41.160,28.60),(41.210,29.02),(41.110,29.28)],
}
ts += ["/** Main roads (simplified from known junctions, not survey data): SVG path per road. */",
       "export const ROAD_PATHS: Record<string, string> = {"]
for k, pts in ROADS.items():
    ts.append(f"  {k}: " + json.dumps("M" + "L".join(f"{x:.0f},{y:.0f}" for x, y in (P(*p) for p in pts))) + ",")
ts += ["};", "", "/** Candidate spots for each road's number shield; the map uses the first one clear of the pin. */",
       "export const ROAD_SHIELDS: Record<string, [number, number][]> = {"]
for k, pts in SHIELDS.items():
    ts.append(f"  {k}: [" + ", ".join(f"[{P(*p)[0]}, {P(*p)[1]}]" for p in pts) + "],")
ts += ["};", "", "/** The three Bosphorus bridges (15 July, Fatih Sultan Mehmet, Yavuz Sultan Selim), as end points. */",
       "export const BRIDGES: [[number, number], [number, number]][] = ["]
for k, (a, b) in BRIDGES.items():
    ts.append(f"  [[{P(*a)[0]}, {P(*a)[1]}], [{P(*b)[0]}, {P(*b)[1]}]], // {k}")
ts += ["];", "", "/** Points of interest, most important first (labels are placed in this order); the label is `projectDetail.map.<key>`. */",
       'export const LANDMARKS: { key: string; kind: "airport" | "mall" | "landmark"; x: number; y: number }[] = [']
for k, kind, la, lo in LANDMARKS:
    x, y = P(la, lo); ts.append(f'  {{ key: "{k}", kind: "{kind}", x: {x}, y: {y} }},')
bx, by = P(41.13, 29.08)
a = P(41.045, 29.03); b = P(41.20, 29.11)
ang = round(math.degrees(math.atan2(b[1]-a[1], b[0]-a[0])))
ts += ["];", "", f"/** Where the Bosphorus label sits, and its angle along the strait. */",
       f"export const BOSPHORUS_LABEL = {{ x: {bx}, y: {by}, angle: {ang} }};", ""]
open(os.path.join(HERE, "..", "..", "src", "data", "istanbulMap.ts"), "w").write("\n".join(ts))
print(W, H, len("\n".join(ts)))
